---
name: Cancelling Duplicates
on:
  workflow_run:
    workflows:
      - 'Deploy'
      - 'Linting (Markdown)'
      - 'Linting (YAML)'
      - 'Pull Request'
    types: ['requested']

jobs:
  cancel-duplicate-workflow-runs:
    name: "Cancel duplicate workflow runs"
    runs-on: ubuntu-latest
    steps:
      - uses: potiuk/cancel-workflow-runs@master
        name: "Cancel duplicate workflow runs"
        with:
          cancelMode: allDuplicates
          token: ${{ secrets.GH_PAT_A }}
          sourceRunId: ${{ github.event.workflow_run.id }}
